# Generated by Django 4.2.3 on 2023-07-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('surface_type', models.CharField(max_length=100)),
                ('osv', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('internal_code', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo_scheme', models.CharField(max_length=200)),
                ('price_with_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('digital_impressions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ots', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espar_code', models.CharField(max_length=100)),
                ('july_2023', models.CharField(max_length=100)),
                ('august_2023', models.CharField(max_length=100)),
                ('september_2023', models.CharField(max_length=100)),
                ('october_2023', models.CharField(max_length=100)),
                ('november_2023', models.CharField(max_length=100)),
                ('december_2023', models.CharField(max_length=100)),
                ('media_material', models.CharField(max_length=200)),
                ('product_restrictions', models.CharField(max_length=200)),
                ('city_district', models.CharField(max_length=100)),
                ('tech_requirements', models.CharField(max_length=200)),
                ('installation_price_with_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reinstallation_price_with_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('software_resolution', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'billboard',
            },
        ),
    ]
