# Generated by Django 4.2.3 on 2023-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='surface_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип поверхности'),
        ),
    ]
