# Generated by Django 4.2.3 on 2023-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_cityinfo_city_alter_cityinfo_surface_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='osv',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Осв'),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='side',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='details',
            name='city_district',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Городской Округ'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='august_2023',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Август 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='december_2023',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Декабрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='espar_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код Эспар'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='july_2023',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Июль 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='november_2023',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ноябрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='october_2023',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Октябрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='september_2023',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сентябрь 2023'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_resolution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Разрешение ПО'),
        ),
    ]
