# Generated by Django 4.2.3 on 2023-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_cityinfo_osv_alter_cityinfo_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='osv',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Осв'),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='side',
            field=models.CharField(blank=True, max_length=111, null=True, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='surface_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип поверхности'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='august_2023',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='Август 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='december_2023',
            field=models.CharField(blank=True, max_length=170, null=True, verbose_name='Декабрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='espar_code',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Код Эспар'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='july_2023',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Июль 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='november_2023',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Ноябрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='september_2023',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Сентябрь 2023'),
        ),
    ]
