# Generated by Django 4.2.3 on 2023-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_cityinfo_city_alter_cityinfo_osv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='july_2023',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Июль 2023'),
        ),
    ]
