# Generated by Django 4.2.3 on 2023-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_metrics_july_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='july_2023',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Июль 2023'),
        ),
    ]
