# Generated by Django 4.2.3 on 2023-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_alter_metrics_august_2023_alter_metrics_july_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='september_2023',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сентябрь 2023'),
        ),
    ]
