# Generated by Django 4.2.3 on 2023-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_alter_metrics_september_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='november_2023',
            field=models.CharField(blank=True, max_length=310, null=True, verbose_name='Ноябрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='october_2023',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Октябрь 2023'),
        ),
    ]
