# Generated by Django 4.2.3 on 2023-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_metrics_november_2023_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='august_2023',
            field=models.CharField(blank=True, max_length=302, null=True, verbose_name='Август 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='october_2023',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Октябрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='september_2023',
            field=models.CharField(blank=True, max_length=301, null=True, verbose_name='Сентябрь 2023'),
        ),
    ]
