# Generated by Django 4.2.3 on 2023-07-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_alter_metrics_august_2023_alter_metrics_october_2023_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='july_2023',
            field=models.CharField(blank=True, max_length=305, null=True, verbose_name='Июль 2023'),
        ),
    ]
