# Generated by Django 4.2.3 on 2023-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_alter_metrics_july_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='august_2023',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Август 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='december_2023',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Декабрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='november_2023',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ноябрь 2023'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='september_2023',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сентябрь 2023'),
        ),
    ]
